releasename: 2.2.9.1
releasetag: 2.2.9.1701
releasebuild: 2.2.9.1701
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
exclude:
 - "bin"
 - "obj"
 - "*.exe"
 - "*.csproj"
 - "*.cs"
