releasename: 2.2.9.1
releasetag: 2.2.9.1701
releasebuild: 2.2.9.1701
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: manual
      type: pages
    values:
      layout: docs
      sidebar: manual     
  -
    scope:
      path: reference
      type: pages
    values:
      layout: docs
      sidebar: reference          
exclude:
 - "bin"
 - "obj"
 - "*.exe"
 - "*.csproj"
 - "*.cs"
