-
  id: b9060d4b-c2d3-49ac-b37f-962e7c3cbe9d
  menu: RSA
  settings:
    - Csr.Rsa.KeyBits
    - Csr.Rsa.SignatureAlgorithm
  compatibility: All platforms
  examples:
    - 
      name: Typical
      cmd: '[‑‑ocsp-must-staple] [‑‑reuse-privatekey]'

-
  id: 9aadcf71-5241-4c4f-aee1-bfe3f6be3489
  menu: EC
  settings:
    - Csr.Ec.CurveName
    - Csr.Ec.SignatureAlgorithm
  compatibility: All platforms
  examples:
    - 
      name: Typical
      cmd: '[‑‑ocsp-must-staple] [‑‑reuse-privatekey]'

- 
  id: ea6a5be3-f8de-4d27-a6bd-750b619b2ee2
  menu: IIS
  compatibility: Windows (admin only)
  examples:
      - 
          name: Typical
          cmd: '[‑‑installationsiteid 14] [‑‑sslport 8443] [‑‑sslipaddress 192.168.0.1]'

- 
  id: 3bb22c70-358d-4251-86bd-11858363d913
  menu: Script
  settings:
    - Script.PowershellExecutablePath
    - Script.Timeout
  compatibility: All platforms
  examples:
      - 
          name: Typical
          cmd: '‑‑script C:\script.bat [‑‑scriptparameters x]'

- 
  id: aecc502c-5f75-43d2-b578-f95d50c79ea1
  menu: None
  compatibility: All platforms

- 
  id: b705fa7c-1152-4436-8913-e433d7f84c82
  menu: Single
  compatibility: All platforms

- 
  id: 874a86e4-29c7-4294-9ab6-6908866847a0 
  menu: Host
  compatibility: All platforms

- 
  id: b7c331d4-d875-453e-b83a-2b537ca12535
  menu: Domain
  compatibility: All platforms

- 
  id: 74a42b2d-8eaa-4f40-ab6a-f55304254143
  menu: Site
  compatibility: Windows (*)

- 
  id: 54deb3ee-b5df-4381-8485-fe386054055b
  menu: IIS
  arguments:
    - hidehttps
  compatibility: Windows (admin only)
  examples:
      - 
          name: Single binding
          cmd: '‑‑host example.com [‑‑siteid 1]'
      - 
          name: More bindings
          cmd: '‑‑host example.com,www.example.com [‑‑siteid 1,2,3] [‑‑commonname common.example.com]'
      - 
          name: All site bindings
          cmd: '‑‑siteid 1 [‑‑commonname common.example.com] [‑‑excludebindings exclude.example.com]'
      - 
          name: Multiple sites
          cmd: '‑‑siteid 1,2,3 [‑‑commonname common.example.com] [‑‑excludebindings exclude.example.com]'
      - 
          name: All sites
          cmd: '‑‑siteid s [‑‑commonname common.example.com] [‑‑excludebindings exclude.example.com]'
      - 
          name: Pattern
          cmd: '‑‑host-pattern *.example.??? [‑‑siteid 1,2,3] [‑‑commonname common.example.com] [‑‑excludebindings exclude.example.com]'
      - 
          name: Regex
          cmd: '‑‑host-regex [a-z]{3}\.example(\.com|\.net) [‑‑siteid 1,2,3] [‑‑commonname common.example.com] [‑‑excludebindings exclude.example.com]'    

- 
  id: e239db3b-b42f-48aa-b64f-46d4f3e9941b
  menu: Manual
  compatibility: All platforms
  examples:
      - 
          name: Typical
          cmd: '‑‑host a.example.com,*.example.com'   

- 
  id: 5c3db0fb-840b-469f-b5a7-0635d8e9a93d
  menu: CSR
  compatibility: All platforms
  examples:
      - 
          name: Typical
          cmd: '‑‑csrfile C:\csr.txt [‑‑pkfile C:\key.txt]'

- 
  id: e30adc8e-d756-4e16-a6f2-450f784b1a97
  menu: Computer Store
  settings:
    - Store.CertificateStore.DefaultStore
    - Store.CertificateStore.PrivateKeyExportable
    - Store.CertificateStore.UseNextGenerationCryptoApi
  compatibility: Windows
  examples:
      - 
          name: Typical
          cmd: '[‑‑certificatestore My] [‑‑keepexisting] [‑‑acl-fullcontrol "network service,administrators"] [‑‑acl-read "myapp"]'  

- 
  id: e57c70e4-cd60-4ba6-80f6-a41703e21031
  menu: .pem
  settings:
    - Store.PemFiles.DefaultPath
    - Store.PemFiles.DefaultPassword
  compatibility: All platforms
  examples:
      - 
          name: Typical
          cmd: '[‑‑pemfilespath C:\Certificates\] [‑‑pempassword ******] [‑‑pemfilesname mycert]' 

- 
  id: 2a2c576f-7637-4ade-b8db-e8613b0bb33e
  menu: .pfx
  settings:
    - Store.PfxFile.DefaultPath
    - Store.PfxFile.DefaultPassword
    - Store.PfxFile.DefaultProtectionMode
  compatibility: All platforms
  examples:
      - 
          name: Typical
          cmd: '[‑‑pfxpassword *****] [‑‑pfxfilepath C:\Certificates\] [‑‑pfxfilename mycert]' 

- 
  id: af1f77b6-4e7b-4f96-bba5-c2eeb4d0dd42
  menu: Central SSL
  settings:
    - Store.CentralSsl.DefaultPath
    - Store.CentralSsl.DefaultPassword
    - Store.CentralSsl.DefaultProtectionMode
  compatibility: All platforms
  examples:
      - 
          name: Typical
          cmd: '[‑‑centralsslstore C:\CentralSSL\] [‑‑pfxpassword *****]'   

- 
  external: true
  id: dbfa91e2-28c0-4b37-857c-df6575dbb388
  menu: Azure
  provider: Microsoft
  compatibility: All platforms
  examples:
    - 
      name: Service Principal
      cmd: '‑‑azuretenantid 8a947dda-3ed2-40dc-8058-d7b212322ed2 ‑‑azureclientid e02a0517-412e-4e0a-996b-2693458a9232 ‑‑azuresecret ***** ‑‑vaultname MyVault ‑‑certificatename MyCertificate'
    -
      name: Managaged Identity
      cmd: '‑‑azureusemsi ‑‑vaultname MyVault ‑‑certificatename MyCertificate'

- 
  external: true
  id: 95ee94e7-c8e2-40e6-a26f-c9fc3afa9fa5
  menu: User Store
  compatibility: All platforms
  examples:
      - 
          name: Typical
          cmd: '[‑‑keepexisting]' 

- 
  id: cfdd7caa-ba34-4e9e-b9de-2a3d64c4f4ec
  compatibility: All platforms

- 
  id: c13acc1b-7571-432b-9652-7a68a5f506c5
  menu: acme-dns
  compatibility: All platforms
  examples:
    - 
        name: Typical
        cmd: '[‑‑acmednsserver https://acme-dns.example.com/]'   

- 
  external: true
  id: 1d4db2ea-ce7c-46ce-b86f-40b356fcf999
  provider: Alibaba
  page: alibaba
  compatibility: All platforms
  examples:
    - 
      name: Typical
      cmd: ‑‑aliyunapiid ***** ‑‑aliyunapisecret ***** [‑‑aliyunserver dns.aliyuncs.com]

- 
  external: true
  id: aa57b028-45fb-4aca-9cac-a63d94c76b4a
  provider: Microsoft
  menu: Azure
  compatibility: All platforms
  examples:
    - 
      name: Service Principal
      cmd: '‑‑azuretenantid 9741a4c9-0e0b-4f35-abbe-9af735194804 ‑‑azureclientid 2a32943f-e46b-469c-a42d-eb5c54bf798d ‑‑azuresecret ***** ‑‑azuresubscriptionid 6c1e8002-c547-4e93-a9b3-7163f51c380e ‑‑azureresourcegroupname myresourcegroup [‑‑azurehostedzone zone.example.com]'
    -
      name: Managaged Identity
      cmd: '‑‑azureusemsi ‑‑azuresubscriptionid 6c1e8002-c547-4e93-a9b3-7163f51c380e ‑‑azureresourcegroupname myresourcegroup [‑‑azurehostedzone zone.example.com]'

- 
  external: true
  id: b61505e9-1709-43fd-996f-c74c3686286c
  provider: Google
  menu: Google
  page: clouddns
  download: googledns
  compatibility: All platforms
  examples:
    - 
      name: Typical
      cmd: ‑‑serviceaccountkey C:\gcp\key.txt ‑‑projectid example

- 
  external: true
  id: 73af2c2e-4cf1-4198-a4c8-1129003cfb75
  menu: Cloudflare
  compatibility: All platforms
  examples:
    -
      name: Typical
      cmd: ‑‑cloudflareapitoken *****

- 
  external: true
  menu: DigitalOcean
  id: 1a87d670-3fa3-4a2a-bb10-491d48feb5db
  compatibility: All platforms
  examples:
    -
      name: Typical
      cmd: ‑‑digitaloceanapitoken *****

- 
  external: true
  id: c9017182-1000-4257-a8da-0553cd1490ec
  menu: DNSExit
  compatibility: All platforms
  examples:
    -
      name: Typical
      cmd: ‑‑apikey *****

- 
  external: true
  id: 13993334-2d74-4ff6-801b-833b99bf231d
  provider: Digicert
  menu: DNS Made Easy
  compatibility: All platforms
  examples:
    -
      name: Typical
      cmd: ‑‑apikey abc ‑‑apisecret *****

- 
  external: true
  id: 0bd9b320-08e0-4bfe-a535-b979886187e4
  menu: Domeneshop
  page: domene
  compatibility: All platforms
  examples:
    -
      name: Typical
      cmd: ‑‑clientid myclientid ‑‑clientsecret *****

- 
  external: true
  id: 2bfb3ef8-64b8-47f1-8185-ea427b793c1a
  menu: DreamHost
  compatibility: All platforms
  examples:
    -
      name: Typical
      cmd: ‑‑apikey *****

- 
  external: true
  id: 966c4c3d-1572-44c7-9134-5e2bc8fa021d
  menu: GoDaddy
  compatibility: All platforms
  examples:
    -
      name: Typical
      cmd: ‑‑apikey mykey ‑‑apisecret *****

- 
  external: true
  id: 7176cc8f-ba08-4b07-aa39-2f5d012c1d5a
  menu: Hetzner
  compatibility: All platforms
  examples:
    -
      name: Typical
      cmd: ‑‑hetznerapitoken ***** [‑‑hetznerzoneId 1234]

- 
  external: true
  id: d1401d1e-b925-407d-a38b-924d67b2d1b5
  menu: Infomaniak
  compatibility: All platforms
  examples:
    -
      name: Typical
      cmd: ‑‑apitoken *****

- 
  external: true
  id: 12fdc54c-be30-4458-8066-2c1c565fe2d9
  provider: Akamai
  menu: Linode
  compatibility: All platforms
  examples:
    -
      name: Typical
      cmd: ‑‑apitoken *****

- 
  external: true
  id: 3b0c3cca-db98-40b7-b678-b34791070d42
  menu: LuaDNS
  page: lua
  compatibility: All platforms
  examples:
    -
      name: Typical
      cmd: ‑‑luadnsusername myusername ‑‑luadnsapikey *****

- 
  id: e239db3b-b42f-48aa-b64f-46d4f3e9941b
  menu: Manual
  compatibility: All platforms

- 
  external: true
  id: c66cc8be-3046-46c2-a0ba-ec4ec3e7fe96
  provider: IBM
  menu: NS1
  compatibility: All platforms
  examples:
    -
      name: Typical
      cmd: ‑‑apikey *****

- 
  external: true
  id: ed5dc9d1-739c-4f6a-854f-238bf65b63ee
  menu: RFC2136
  compatibility: All platforms
  examples:
    -
      name: Typical
      cmd: ‑‑serverhost 10.10.10.10 [‑‑serverport 53] ‑‑tsigkeyname mykey ‑‑tsigkeysecret ***** [‑‑tsigkeyalgorithm md5]

- 
  external: true
  id: 4e5dc595-45c7-4461-929a-8f96a0c96b3d
  menu: Route 53
  provider: Amazon AWS
  compatibility: All platforms
  examples:
    -
      name: User
      cmd: ‑‑route53accesskeyid mykeyid ‑‑route53secretaccesskey *****
    - 
      name: IAM role
      cmd: ‑‑route53iamrole myrole

- 
  id: 8f1da72e-f727-49f0-8546-ef69e5ecec32
  menu: Script
  settings:
    - Script.PowershellExecutablePath
    - Script.Timeout
    - Validation.DisableMultiThreading
  compatibility: All platforms
  examples:
    -
      name: Create script only
      cmd: ‑‑dnscreatescript c:\create.ps1 [‑‑dnscreatescriptarguments {args}]
    -
      name: Separate create and delete scripts
      cmd: ‑‑dnscreatescript c:\create.ps1 ‑‑dnsdeletescript c:\delete.ps1 [‑‑dnscreatescriptarguments {args}] [‑‑dnsdeletescriptarguments {args}]
    - 
      name: Combined script
      cmd: ‑‑dnsscript c:\create-and-delete.ps1 [‑‑dnscreatescriptarguments {args}] [‑‑dnsdeletescriptarguments {args}]

- 
  external: true
  id: 3693c40c-7c2f-4b70-aead-27869d8cbdf3
  menu: Simply.com
  compatibility: All platforms
  examples:
    -
      name: Typical
      cmd: ‑‑account myaccount ‑‑apikey *****

- 
  external: true
  id: 6ea628c3-0f74-68bb-cf17-4fdd3d53f3af
  menu: Tencent
  compatibility: All platforms
  examples:
    -
      name: Typical
      cmd: ‑‑tencentapiid myapiid ‑‑tencentapikey *****

- 
  external: true
  id: c49a7a9a-f8c9-494a-a6a4-c6b9daae7d9d
  menu: TransIP
  compatibility: All platforms
  examples:
    -
      name: Inline key
      cmd: ‑‑transip-login mylogin ‑‑transip-privatekey "---- BEGIN PRIVATE KEY ---- **** ---- END PRIVATE KEY ----"
    -
      name: Key on disk
      cmd: ‑‑transip-login mylogin ‑‑transip-privatekeyfile C:\transip.key

- 
  id: c7d5e050-9363-4ba1-b3a8-931b31c618b7
  menu: Self-hosting
  settings:
    - Execution.DefaultPreExecutionScript
    - Execution.DefaultPostExecutionScript
  compatibility: All platforms
  examples:
    -
      name: Typical
      cmd: '[‑‑validationport 8080] [‑‑validationprotocol https]'

- 
  id: 1c77b3a4-5310-4c46-92c6-00d866e84d6b
  menu: Filesystem
  settings:
    - Validation.CleanupFolders
  compatibility: All platforms
  examples:
    -
      name: Path from IIS
      cmd: '‑‑validationsiteid 1'
    -
      name: Manual path
      cmd: '‑‑webroot c:\httpdocs\'

-
  page: ftps
  id: bc27d719-dcf2-41ff-bf08-54db7ea49c48
  menu: FTP(S)
  settings:
    - Validation.CleanupFolders
    - Validation.Ftp.UseGnuTls 
  compatibility: All platforms
  examples:
    -
      name: Typical
      cmd: ‑‑webroot ftps://ftp.example.com:990/path/ ‑‑username simpleacme ‑‑password *****

- 
  id: 048aa2e7-2bce-4d3e-b731-6e0ed8b8170d
  menu: SFTP
  settings:
    - Validation.CleanupFolders
  compatibility: All platforms
  examples:
    -
      name: Typical
      cmd: '‑‑webroot sftp://example.com/path/ ‑‑username simple-acme ‑‑password *****'

- 
  id: 7e191d0e-30d1-47b3-ae2e-442499d33e16
  menu: WebDav
  settings:
    - Validation.CleanupFolders
  compatibility: All platforms
  examples:
    -
      name: Typical
      cmd: '‑‑webroot webdav://example.com/path/ ‑‑username simple-acme ‑‑password *****'

- 
  external: true
  id: 11ba2994-ea59-4f2f-b9eb-0eaa2fa3cbfa
  menu: REST
  compatibility: All platforms
  examples:
    -
      name: Typical
      cmd: '‑‑rest-securitytoken ***** [‑‑rest-usehttps]'

- 
  id: a1565064-b208-4467-8ca1-1bd3c08aa500
  menu: Self-hosting
  compatibility: All platforms
  examples:
    -
      name: Typical
      cmd: '[‑‑validationport 4330]'