Client:
  ClientName:
    type: string
    default: "simple-acme"
    description: The name of the client, which comes back in several 
      places like the scheduled task name, Windows event viewer and 
      the <code>ConfigurationPath</code>.

  ConfigurationPath:
    type: string
    subtype: path
    default: null
    description: Change the location where the program stores 
      its (temporary) files. If not specified this resolves 
      to <code>%programdata%\{ClientName}\{BaseUri}</code>. Values should be 
      JSON-encoded, e.g. <code>"C:\\"</code> (note the double backslash).

  LogPath:
    type: string
    subtype: path
    default: null
    description: The path where log files for the past 31 days are stored. 
      If not specified or invalid, this defaults to {ConfigurationPath}\Log. 
      Values should be JSON-encoded, e.g. <code>"C:\\"</code> (note the double 
      backslash).

  VersionCheck:
    type: bool
    default: false
    description: Automatically check for new versions at startup. 

UI:
  DateFormat:
    type: string
    default: "yyyy/M/d H:mm:ss"
    description: A string that is used to format the date of the 
      certificates friendly name. <a href="https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings?redirectedfrom=MSDN">Documentation</a> 
      for possibilities is available from Microsoft.

  PageSize:
    type: number
    default: 50
    description: The number of items to display per page in list views.

  TextEncoding:
    type: string
    default: utf-8
    description: Encoding to use for the console output. A list of 
      possible values can be found <a href="https://learn.microsoft.com/en-us/dotnet/api/system.text.encoding?view=netcore-3.0">here</a>. 
      For certain languages <code>"unicode"</code> might give better results 
      displaying the characters, but note that this reduces compatibility with 
      other programs processing the output.

  Color:
    Background:
      type: string
      description: When set to <code>"black"</code>, the background color 
        for the UI will be forced to black using VT100 escape sequences. 
        This only works in modern terminals, i.e. nothing before Windows 2016 
        / Windows 10.

ACME:
  DefaultBaseUri:
    type: string
    subtype: uri
    default: https://acme-v02.api.letsencrypt.org/
    description: Default ACMEv2 endpoint to use when none is specified with the command line.
  
  DefaultBaseUriTest:
    type: string
    subtype: uri
    default: https://acme-staging-v02.api.letsencrypt.org/
    description: Default ACMEv2 endpoint to use when none is specified with the command line and the <code>--test</code> switch is activated.
  
  DefaultBaseUriImport:
    type: string
    subtype: uri
    default: "https://acme-v01.api.letsencrypt.org/"
    description: Default ACMEv1 endpoint to import renewal settings from.
  
  PostAsGet:
    type: boolean
    default: true
    description: Use POST-as-GET mode as defined in <a href="https://datatracker.ietf.org/doc/html/rfc8555#section-6.3">RFC8555 section 6.3</a>, 
      as required by Let's Encrypt since November 2020.

  ValidateServerCertificate:
    type: boolean
    default: true
    description: Set this to <code>false</code> to disable certificate validation 
      of the ACME endpoint. Note that this is a security risk, it's only intended 
      to connect to internal/private ACME servers with self-signed certificates.

  RetryCount:
    type: number
    default: 15
    description: Maximum numbers of times to refresh validation and order 
      status, while waiting for the ACME server to complete its tasks.

  RetryInterval:
    type: number
    default: 5
    description: Amount of time in seconds to wait for each retry.

  PreferredIssuer:
    type: string
    description: In some exceptional cases an ACME service will offer multiple 
      certificates signed by different root authorities. This setting can be 
      used to give a preference. I.e. <code>"ISRG Root X1"</code> can be used 
      to prefer Let's Encrypt self-signed chain over the backwards compatible 
      <code>"DST Root CA X3"</code>. Note that this only really works for 
      Apache and other software that uses <code>.pem</code> files to store 
      certificates. Windows has its own opinions about how chains should be 
      built that are difficult to influence. For maximum compatibility with 
      legacy clients we recommend using an alternative provider like ZeroSSL.

Execution:
  DefaultPreExecutionScript:
    type: string
    subtype: path
    description: Path to a script that is executed before renewing a 
      certificate. This may be useful to temporarely relax security measures, 
      e.g. opening port 80 on the firewall.

  DefaultPostExecutionScript:
    type: string
    subtype: path
    description: Path to a script that is called after renewing a certificate, 
      this may be useful to undo any actions taken by the script configured as 
      the <code>DefaultPreExecutionScript</code>. Not to be confused with the 
      <a href="/reference/plugins/installation/script">script installation</a> 
      plugin. The difference is that the installation plugin can be configured 
      separately for each renewal and has access to a lot more context about
      the new and previous certificates. Also when the installation script 
      fails, the renewal will be retried later. That is not the case for the 
      pre/post execution scripts. Any errors there are logged but otherwise 
      ignored.

Proxy:
  Url: 
    type: string
    subtype: uri
    default: "[System]"
    description: Configures a proxy server to use for communication with the 
      ACME server and other HTTP requests done by the program. The default 
      setting (which is equivalent to <code>"[wininet]"</code>) uses the proxy 
      as defined by the legacy Windows Internet API. You can also use 
      <code>"[winhttp]"</code> to use the more modern Windows HTTP API. 
      Honestly <code>"[winhttp]"</code> should be the default, but isn't because 
      of backwards compatiblity. Leaving the value empty/null tries to bypass 
      any proxy. You can also configure a specific proxy URL.

  Username:
    type: string
    description: Username used to access the proxy server.

  Password:
    type: string
    subtype: secret
    description: Password used to access the proxy server. 
      This may be a reference to the <a href="/manual/advanced-use/secret-management">secret vault</a>.

Cache:
  Path: 
    type: string
    subtype: path
    description: The path where certificates, request files and private keys 
      are cached. If not specified or invalid, this defaults to {ConfigurationPath}\Certificates. 
      If you are using <a href="/reference/plugins/store/centralssl">CentralSsl</a>, this can not be set to the same path. Values 
      should be JSON-encoded, e.g. <code>"C:\\"</code> (note the double backslash).

  ReuseDays:
    type: number
    default: 1
    description: When renewing or re-creating a previously requested certificate 
      that has the exact same set of domain names, the program will used a cached 
      version for this many days, to prevent users from running into <a href="https://letsencrypt.org/docs/rate-limits/">rate limits</a> 
      while experimenting. Set this to a high value if you regularly re-request 
      the same certificates, e.g. for a Continuous Deployment scenario. 
    
      Setting this to 0 will not entirely disable the cache (the program also 
      needs the files for different reasons), but it will prevent the files from 
      being used for renewals and will also ensure that no private key material 
      is stored in the cache, unless specifically requested by 
      <code>--reuse-privatekey</code>.

  DeleteStaleFiles:
    type: boolean
    default: false
    description: Automatically delete files older than <code>DeleteStaleFileDays</code> 
      many days from the {CertificatePath} folder. Running with default settings, 
      these should only be long-expired certificates, generated for abandoned renewals.
  
  DeleteStaleFileDays:
    type: number
    default: 120
    description: This value should be increased if you are working with 
      long-lived certificates and enable <code>DeleteStaleFiles</code>.

ScheduledTask:
  RenewalDays:
    type: number
    default: 55
    description: The number of days to renew a certificate after. Let's Encrypt 
      certificates are currently for a max of 90 days so it is advised to not 
      increase the days much. If you increase the days, please note that you 
      will have less time to fix any issues if the certificate doesn't renew 
      correctly.

  RenewalDaysRange:
    type: number
    default: 0
    description: To spread service load, program run time and/or to minimize 
      downtime, those managing a large amount of renewals may want to spread 
      them out of the course of multiple days/weeks. The number of days 
      specified here will be substracted from <code>RenewalDays</code> to 
      create a range within which the renewal will e processed. E.g. if 
      <code>RenewalDays</code> is 55 and <code>RenewalDaysRange</code> is 10, 
      the renewal will be processed between 45 and 55 days after issuing.

      If you use an order plugin to split your renewal into multiple orders, 
      orders may run on different days.

  RenewalDisableServerSchedule:
    type: boolean
    default: false
    description: By default, servers implementing ARI may suggest that 
      renewals should happen earlier than the regularly scheduled moment. 
      When set to <code>true</code>, ARI suggestions will be ignored 
      (not recommended).

  RenewalMinimumValidDays:
    type: number
    default: 7
    description: The minimum number of days a certificate should still be 
      valid. If the certificate is valid for a smaller number of days, it 
      will be renewed regardless of the <code>RenewalDays</code> setting.

  StartBoundary:
    type: string
    subtype: time
    default: "09:00:00"
    
  ExecutionTimeLimit:
    type: string
    subtype: time
    default: "02:00:00"

  RandomDelay:
    type: string
    subtype: time
    default: "04:00:00"

Notifications:
  SmtpServer:
    type: string
    subtype: host
    
  SmtpPort:
    type: number
    default: 25

  SmtpUser:
    type: string

  SmtpPassword:
    type: string
    subtype: secret

  SmtpSecure:
    type: boolean
    default: false

  SmtpSecureMode:
    type: number
    default: 1

  SmtpSenderName:
    type: string
    
  SenderAddress:
    type: string
    subtype: email

  ReceiverAddresses:
    type: string[]
    subtype: email

  EmailOnSuccess:
    type: boolean
    default: false

  ComputerName:
    type: string

Security:
  EncryptConfig:
      type: boolean
      default: true

  FriendlyNameDateTimeStamp:
      type: boolean
      default: true

Script:
  Timeout:
    type: number
    default: 600

  PowershellExecutablePath:
    type: string
    subtype: path
    default: "powershell.exe"

Source:
  DefaultSource:
    type: string

Validation:
  DefaultValidation:
    type: string

  DefaultValidationMode:
    type: string

  DisableMultiThreading:
    type: boolean
    default: true

  ParallelBatchSize:
    type: number
    default: 100

  CleanupFolders:
    type: boolean
    default: true

  PreValidateDns:
    type: boolean
    default: true

  PreValidateDnsRetryCount:
    type: number
    default: 5

  PreValidateDnsRetryInterval:
    type: number
    default: 30

  AllowDnsSubstitution:
    type: boolean
    default: true

  DnsServers:
    type: string[]
    subtype: host
    default: "[ \"[System]\" ]"

  Ftp:
    UseGnuTls:
      type: boolean
      default: false

Order:
  DefaultOrder:
    type: string

  DefaultValidDays:
    type: number

Csr:
  DefaultCsr:
    type: string
    
  Rsa:
    KeyBits:
      type: number
      default: 3072

    SignatureAlgorithm:
      type: string
      default: SHA512withECDSA

  Ec:
    CurveName: 
      type: string
      default: secp384r1
      description: The curve used to use to generated key pairs on.

    SignatureAlgorithm:
      type: string
      default: SHA512withECDSA

Store:
  DefaultStore:
    type: string

  CertificateStore:
    DefaultStore:
      type: string

    PrivateKeyExportable:
      type: boolean
      default: false

    UseNextGenerationCryptoApi:
      type: boolean
      default: false

  CentralSsl:
    DefaultPath:
      type: string
      subtype: path

    DefaultPassword:
      type: string
      subtype: secret

  PemFiles:
    DefaultPath:
      type: string
      subtype: path

    DefaultPassword:
      type: string
      subtype: secret  

  PfxFile:
    DefaultPath:
      type: string
      subtype: path

    DefaultPassword: 
      type: string
      subtype: secret  

Installation:
  DefaultInstallation:
      type: string

Secrets:
  Json:
    FilePath:
      type: string
      subtype: path  