client:
  - Client.ClientName
  - Client.ConfigurationPath
  - Client.LogPath
  - Client.VersionCheck
ui:
  - UI.DateFormat
  - UI.PageSize
  - UI.TextEncoding
  - UI.Color.Background
acme:
  - Acme.DefaultBaseUri
  - Acme.DefaultBaseUriTest
  - Acme.DefaultBaseUriImport
  - Acme.PostAsGet
  - Acme.ValidateServerCertificate
  - Acme.RetryCount
  - Acme.RetryInterval
  - Acme.PreferredIssuer
  - Acme.MaxDomains
  - Acme.PublicSuffixListUri
execution:
  - Execution.DefaultPreExecutionScript
  - Execution.DefaultPostExecutionScript
proxy:
  - Proxy.Url
  - Proxy.UserName
  - Proxy.Password
cache:
  - Cache.Path
  - Cache.ReuseDays
  - Cache.DeleteStaleFiles
  - Cache.DeleteStaleFilesDays
  - Cache.ProtectionMode
scheduledtask:
  - ScheduledTask.RenewalDays
  - ScheduledTask.RenewalDaysRange
  - ScheduledTask.RenewalDisableServerSchedule
  - ScheduledTask.RenewalMinimumValidDays
  - ScheduledTask.StartBoundary
  - ScheduledTask.ExecutionTimeLimit
  - ScheduledTask.RandomDelay
notification:
  - Notification.SmtpServer
  - Notification.SmtpPort
  - Notification.SmtpUser
  - Notification.SmtpPassword
  - Notification.SmtpSecure
  - Notification.SmtpSecureMode
  - Notification.SenderName
  - Notification.SenderAddress
  - Notification.ReceiverAddresses
  - Notification.EmailOnSuccess
  - Notification.ComputerName
security:
  - Security.EncryptConfig
  - Security.FriendlyNameDateTimeStamp
script:
  - Script.Timeout
  - Script.PowershellExecutablePath
source:
  - Source.DefaultSource
validation:
  - Validation.DefaultValidation
  - Validation.DefaultValidationMode
  - Validation.DisableMultiThreading
  - Validation.ParallelBatchSize
  - Validation.CleanupFolders
  - Validation.PreValidateDns
  - Validation.PreValidateDnsRetryCount
  - Validation.PreValidateDnsRetryInterval
  - Validation.PreValidateDnsLocal
  - Validation.DnsPropagationDelay
  - Validation.AllowDnsSubstitution
  - Validation.DnsServers
  - Validation.Ftp.UseGnuTls
order:
  - Order.DefaultOrder
  - Order.DefaultValidDays
csr:
  - Csr.DefaultCsr
  - Csr.Rsa.KeyBits
  - Csr.Rsa.SignatureAlgorithm
  - Csr.Ec.CurveName
  - Csr.Ec.SignatureAlgorithm
store:
  - Store.DefaultStore
certificatestore:
  - Store.CertificateStore.DefaultStore
  - Store.CertificateStore.PrivateKeyExportable
  - Store.CertificateStore.UseNextGenerationCryptoApi
centralssl:
  - Store.CentralSsl.DefaultPath
  - Store.CentralSsl.DefaultPassword
  - Store.CentralSsl.DefaultProtectionMode
pemfiles:
  - Store.PemFiles.DefaultPath
  - Store.PemFiles.DefaultPassword
pfxfile:
  - Store.PfxFile.DefaultPath
  - Store.PfxFile.DefaultPassword
  - Store.PfxFile.DefaultProtectionMode
p7bfile:
  - Store.P7bFile.DefaultPath
installation:
  - Installation.DefaultInstallation
secrets:
  - Secrets.Json.FilePath
  - Secrets.Script.Get
  - Secrets.Script.GetArguments
